# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &defaults
  adapter: postgresql
  encoding: utf8
  database: overlord_development
  username: overlord
  password: overlord
  su_username: markojurincic
  su_password: sewen7sewen

test:
  <<: *defaults
  database: overlord_test

production:
  adapter: postgresql
  encoding: utf8
